defaults:
  - latent_dynamics: phase_amplitude

_target_: deep_isochron.model.PhaseAmplitudeAutoencoder
obs_dim: ${..data.dim}
mlp_depth: 2
mlp_width: 100
activation:
  _target_: hydra.utils.get_method
  path: jax.nn.relu
key:
  _target_: jax.random.key
  seed: 0
